# Genome Annotation {#annot}

## Annotating

Finally, we will annotate the genome, meaning that we will identify putative genes and then compare these genes against a database of known genes to find which ones align the best.

The identification of putative genes can be done in a variety of ways. One way to find these regions requires the observation that regions of DNA that are translated into protein start with a start codon (ATG) and end with a stop codon (TAG, TAA, or TGA). If a genome were random, then after encountering a start codon, we would expect to see a stop codon after about 64/3 ~ 21 codons. But real genes are typically much, much longer than 21 codons. As a result, in simple organisms like viruses and bacteria, a great way to find genes is to look for long stretches of codons connecting a start codon to a stop codon, with no intermediate stop codons.

Once we have found putative genes along the genome, we can compare them against a database of genes using an algorithm called BLAST.

These two steps are taken by our next tool, called Prokka, which is used to annotate the genomes of viruses, bacteria, and archaea. It can be found under “Annotation” on Galaxy. 

1. Under “Contigs to annotate”, select our contigs from the SPAdes run. 

2. Set “Kingdom” to “Bacteria” and leave all other parameters to default. Note that Prokka only annotates contigs of length at least 200. Select whether you would like an Email on completion, and click “Run”.

The entire process of annotating our genome should not take more than a few seconds. Isn’t bioinformatics great?

Prokka produces a collection of output files in the history on the right. 
- The .fna file contains the contigs included in the annotation.
- The .gff file contains regions identified by Prokka as genes. 
- The .ffn file contains nucleotide sequences of the annotated genes, and the .faa file contains their translated amino acid sequences.

More detailed descriptions of the outputs can be found at https://github.com/tseemann/prokka#output-files

3. View the .gff file containing regions identified by Prokka as putative genes. How many are there? What is the longest and shortest one?

## Viewing the annotation

Prokka contains the annotation information in these files, but what a biologist would really like is a visualization of its genes and what they have been predicted to be. So to visualize our annotation contained in the .gff file, we will use a genome browser tool called “JBrowse”

1. Click (on the left side of screen) "Statistics and Visualization" > "Graph/Display data" > "Jbrowse"
2. Under “Reference genome to display” select “use genome from history”
3. Under “Select reference genome” select the .fna file from the prokka annotation outputs.
4. Click “insert track group” and then “insert annotation track”
5. Under “GFF/GFF3/BED Track Data” select the .gff file from the prokka annotation outputs
6. Click “Run tool”
7. Make sure to have both boxes under “Available Tracks” checked on

JBrowse should be very quick. When it is finished, click view file, which is an HTML file that we can view in the browser. (It may take a moment to load.)

It seems like nothing is there, but on the left side of the page, click on “Prokka on data XXX: gff” to show our  annotation of the genome. Zoom out to see it. The arrows point in the direction to indicate which strand of the genome the gene is found on. 

You can click on the genes as you like to obtain information about their length and what in the database they were found to be similar to (if anything). The annotation score of a protein represents how much experimental evidence backing up this protein. A high score means that if we find a putative gene that is a hit against it, we have a high degree of certainty that our gene serves a similar function.

- Why do you think that some genes are labeled “hypothetical proteins”?

Now  we can start investigating the bacteria’s individual genes. Which one should we focus on? How has the gene mutated as the virus spread around the world? And how do these mutations affect the function of the protein?